global:
  scrape_interval: 2s

scrape_configs:
  - job_name: "app"
    static_configs:
      - targets: ["app:10000"]

  - job_name: "budget_service"
    static_configs:
      - targets: ["budget_service:10300"]

  - job_name: "auth_service"
    static_configs:
      - targets: ["auth_service:10200"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
