global:
  scrape_interval: 2s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "/etc/prometheus/alerts.yml"

scrape_configs:
  - job_name: "app"
    static_configs:
      - targets: ["app:10000"]

  - job_name: "budget_service"
    static_configs:
      - targets: ["budget_service:8800"]

  - job_name: "auth_service"
    static_configs:
      - targets: ["auth_service:8700"]

  - job_name: "finance_service"
    static_configs:
      - targets: ["finance_service:8910"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "docker_exporter"
    static_configs:
      - targets: ["docker_exporter:9417"]
